<?php
/**
 * Config - an example for setting up system settings.
 * When you are done editing, rename this file to 'Config.php'.
 *
 * @author David Carr - dave@daveismyname.com
 * @author Virgil-Adrian Teaca - virgil@giulianaeassociati.com
 * @version 3.0
 */

use Core\Config;
use Foundation\Application;


/**
 * Set the Framework version.
 */
define('VERSION', Application::VERSION);

/**
 * PREFER to be used in Database calls or Session data, default is 'nova_'
 */
define('PREFIX', 'nova_');

/**
 * Setup the Config API Mode.
 * For using the 'database' mode, you need to have a database, with a table generated by 'scripts/nova_options'
 */
define('CONFIG_STORE', 'files'); // Supported: "files", "database"

/**
 * Setup the Profiler configuration
 */
Config::set('profiler', array(
    'useForensics' => false,
    'withDatabase' => false,
));

/**
 * Setup the Google reCAPTCHA configuration
 */
Config::set('recaptcha', array(
    'active'  => false,
    'siteKey' => '',
    'secret'  => '',
));

/**
 * Include the configuration files located on application's Config directory.
 *
 * DO NOT MODIFY THE FOLLOWING CODE:
 */
foreach (glob(APPDIR .'Config/*') as $path) {
    if (is_readable($path)) require $path;
}
